CREATE TABLE IF NOT EXISTS user (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    role VARCHAR(50) NOT NULL,
    email VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(50) NOT NULL,
);

CREATE TYPE role_enum AS ENUM ('ADMIN', 'USER');

ALTER TABLE user
ADD COLUMN role role_enum DEFAULT 'USER' NOT NULL;