CREATE TABLE IF NOT EXISTS product (
    id SERIAL PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
	price INT NOT NULL,
	stock INT NOT NULL,
    type VARCHAR(50) NOT NULL,
	userId INT NOT NULL,
    FOREIGN KEY(userId) REFERENCES "user"(id) ON DELETE CASCADE
);